### ISSUE TITLE
Could I source update after than save my folder?

### ISSUE THREAD

**Issue by fivetop** [gdelgiovine/WisejPubsDemoApp#1]
Could I source update after than save my folder?

https://github.com/fivetop/Wisej3-PubsDemoApp

![이미지 007](https://user-images.githubusercontent.com/50413/187342499-741453ce-4303-4245-8941-d35fbace2ffa.png)

**Comment by gdelgiovine** [comment]
The original repository is "closed", but you can fork your own. Remember that the required assembly BasicDAL.dll (the ORM) is not yet avalaible as source code.

**Comment by fivetop** [comment]
thank u.. have a nice day..
